### ISSUE TITLE
Get body function getting logged

### ISSUE THREAD

**Issue by ThrivikramGR** [morungos/node-word-extractor#27]
``var WordExtractor = require("word-extractor");``
``var extractor = new WordExtractor();``
``var extracted = extractor.extract("worldd.doc");``
``extracted.then(function (doc) {``
    ``console.log(doc.getBody);``
``});``

**Code produces some getBody(shouldFilter) {} as output, instead of the file body.**

``ƒ getBody(shouldFilter) {``
    ``if (shouldFilter == null) { ``
      ``shouldFilter = true; ``
    ``}``
    ``const start = 0;``
    ``const string = this.getTextRange(start, start + this.boundaries.ccpText);``
   `` return filter(string, shouldFilter);``
 `` }``

**Comment by morungos** [comment]
Hmmm, this is more a documentation issue than anything to do with the actual logic. The actual code shown as a sample is:

```
const WordExtractor = require("word-extractor"); 
const extractor = new WordExtractor();
const extracted = extractor.extract("file.doc");

extracted.then(function(doc) { console.log(doc.getBody()); });
```

i.e., we're suggesting logging `doc.getBody()` not `doc.getBody`. That's why the issue is logged, as the second logs the `getBody` method itself, it doesn't call it. Can't really see a way to make this better, sorry.
